version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: orderflow
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
